version: '2'

services:
  app:
    image: brunoluiz/pru-bot
    env_file: .env.development
    build:
      args:
        - NODE_ENV=development
      context: .
    volumes:
      - .:/opt/app
      - dummy:/opt/app/node_modules
    ports:
      - 8080:8080
      - 9229:9229
    links:
      - mongodb:mongodb.host
      - pru-menus:pru-menus.host
    command: ../node_modules/.bin/nodemon -L ./app.js --inspect=0.0.0.0:9229

  pru-menus:
    image: brunoluiz/pru-menus
    environment:
      - MONGODB_URI=mongodb://mongodb.host/pru-menu
      - AUTH_USER=test
      - AUTH_PASSWORD=test
      - PORT=9000
    ports:
      - 9000:9000
    links:
      - mongodb:mongodb.host

  mongodb:
    image: mongo:3.4
    ports:
      - 27017:27017

volumes:
  dummy:
